#!/usr/bin/env bash

clear

if [ "$EUID" -ne 0 ]
  then echo "This script requires root access, please run as root or use \"sudo ./new-server\""
  exit
fi

file="/mnt/c/Windows/System32/drivers/etc/hosts"
chmod 777 $file

echo -e "Server name: \c"
read domain
domain=$domain

echo -e "Root folder (leave empty to use the server name): \c"
read rootpath
rootpath=$rootpath
if [ "$rootpath" == '' ]
    then rootpath=$domain
fi

directory=`php -f ./php/directory.php $rootpath`
mkdir $directory

configFileContent=`php -f ./php/new-server.php $directory $domain`

echo -e $configFileContent > /etc/nginx/sites-available/$rootpath.conf
ln -s /etc/nginx/sites-available/$rootpath.conf /etc/nginx/sites-enabled/$rootpath.conf
service nginx restart

hostsFile=`php -f ./php/hosts.php $domain`
echo $hostsFile

echo "Copying index.php to new directory"
cp ./php/index.php $directory/index.php

echo "New server created!"