#!/usr/bin/env bash

clear

if [ "$EUID" -ne 0 ]
  then echo "This script requires root access, please run as root or use \"sudo ./remove\""
  exit
fi

echo "Removing PHP... (this may take a few minutes)"
apt-get remove php* --yes > /dev/null

#echo "Cleaning PHP directories..."
#rm -rf /etc/php

echo "Finished removing PHP."

echo "Removing Nginx... (this may take a few minutes)"
apt-get remove nginx* --yes > /dev/null

#echo "Cleaning Nginx directories..."
#rm -rf /etc/nginx
#rm -rf /var/www

echo "Finished removing Nginx."

echo "Removing mariadb... (this may take a few minutes)"
apt-get remove mariadb* --yes > /dev/null

